const ja = {
  tagline: '指で印を結んで召喚せよ', practice: 'カメラなしで練習', howto: '遊び方', privacy: 'カメラと記録について',
  steps: [['3つの印を覚える', '一瞬だけ光る呪文を、順番どおりに。'], ['指で印を結ぶ', 'カチン！ 手元に魔法陣が増えていく。'], ['両手を前へ、RELEASE!', '超絶魔法か、予想外の何か。']],
  camera: 'FRONT CAMERA', demo: 'PRACTICE', pause: '一時停止', resume: '再開', exit: 'ゲーム一覧へ', loading: '指印の認識モデルを準備しています…', requesting: 'インカメラの許可を待っています…', error: 'カメラを許可するか、カメラなしの練習を選ぼう。', modelError: '認識の準備に失敗しました。再試行か練習を選ぼう。', retryCamera: 'カメラを再試行', lost: '手を中央へ。手首から指先まで映そう。', paused: '準備ができたら再開しよう。',
  coach: '指を少しカメラへ向ける', small: '手を少しカメラに近づける', hold: 'その印を、少しだけキープ', neutral: '次の印へ。同じ印は一度ほどく', release: '両手を開いて、少し前へ出す', armed: '魔法をセット！ 発動を待とう', memory: '印を覚えよう。すぐに消える', demoHint: '1〜5で指印、RでRELEASE。ボタンでもOK。', cameraHint: '印は片手、RELEASEは両手。タップでも発動できます。', skip: 'チュートリアルをスキップ', tutorial: 'まずは同じ印をまねしよう', faceChoice: 'リプレイに映る自分の見た目', ORIGINAL: 'そのまま', EFFECT: '顔を魔法の仮面に', HIDE: 'カメラ映像を隠す', creatorNotice: '15秒の挑戦 → 7秒の自動リプレイ。動画は音声なし。保存は自分で選べます。', again: 'もう一度、詠唱する', next: '次のゲーム', share: '友達に挑戦状', replay: 'リプレイ', save: '7秒動画を保存', local: '映像は端末のメモリに一時保持。退出で破棄されます。', silent: '保存動画は音声なしです。', preparing: '7秒動画を作成中…', saved: '動画を保存しました。', unsupported: 'このブラウザでは動画保存に対応していません。', saveError: '動画を作成できませんでした。もう一度試してください。', book: '発見した魔法', newSpell: '新しい魔法を発見！', choose: '今回の対抗呪文',
};
const en = {
  tagline: 'Make the signs. Summon your magic.', practice: 'Camera-free practice', howto: 'HOW TO PLAY', privacy: 'Camera & recording',
  steps: [['Remember the three signs', 'A spell appears. Then it disappears.'], ['Make the signs in order', 'Click! Another magic circle locks on.'], ['Both palms forward. RELEASE!', 'Epic magic. Or something very unexpected.']],
  camera: 'FRONT CAMERA', demo: 'PRACTICE', pause: 'Pause', resume: 'Resume', exit: 'Back to games', loading: 'Preparing hand-sign recognition…', requesting: 'Waiting for front-camera permission…', error: 'Allow your camera, or try camera-free practice.', modelError: 'Recognition could not start. Retry or choose practice.', retryCamera: 'Retry camera', lost: 'Center a hand. Keep wrist and fingertips visible.', paused: 'Resume when you are ready.',
  coach: 'Turn your fingers a little toward the camera', small: 'Bring your hand a little closer', hold: 'Hold that sign for a moment', neutral: 'Next sign. Relax before repeating a sign', release: 'Open both palms, then push forward', armed: 'Spell armed. Wait for the reveal', memory: 'Remember. These signs will disappear', demoHint: '1–5: signs. R: RELEASE. Buttons work too.', cameraHint: 'One hand: signs. Both palms: release. Tap also works.', skip: 'Skip tutorial', tutorial: 'Copy this sign to start', faceChoice: 'Your appearance in the replay', ORIGINAL: 'Your real camera image', EFFECT: 'A magic mask over your face', HIDE: 'Hide all camera images', creatorNotice: '15-second challenge → 7-second auto replay. Saved video is silent. You choose when to save.', again: 'CAST AGAIN', next: 'NEXT GAME', share: 'CHALLENGE A FRIEND', replay: 'REPLAY', save: 'SAVE 7s VIDEO', local: 'Frames stay temporarily in device memory and are discarded on exit.', silent: 'Saved video has no audio.', preparing: 'Making your seven-second video…', saved: 'Video saved.', unsupported: 'Video saving is unavailable in this browser.', saveError: 'Could not create the video. Try again.', book: 'Discovered spells', newSpell: 'NEW SPELL DISCOVERED!', choose: 'Your counterspell',
};
export const copy = locale => locale === 'ja' ? ja : en;
