import './style.css';
import town from './assets/town-v1.webp';
import { mountReplay } from './replay.js';
export function launchMarkup(game,locale){const ja=locale==='ja';return `<section class="sd-entry"><div class="sd-cover" style="background-image:url('${town}')"><span>EXP-058 · 30 SEC</span><h1>FINGER GUN<br><em>SHOWDOWN</em></h1><p>POINT. SAY BAN.</p></div><div class="sd-entry-copy"><p>${ja?'君の指が、町いちばんの早撃ちになる。':'Your finger. The fastest draw in town.'}</p><p>${ja?'指で狙う → 口を開けてBAN! → 手を下げてリロード。青い市民は撃たない。':'Point → open mouth: BAN! → lower hand to reload. Protect blue civilians.'}</p><label><input type="checkbox" class="sd-creator"> CREATOR · ${ja?'7秒のベストシーンを端末内に記録':'Keep a local 7-second highlight'}</label><label>FACE <select class="sd-face-mode"><option>ORIGINAL</option><option>EFFECT</option><option>HIDE</option></select></label><div class="launch-actions"><button class="launch-camera" disabled>DRAW! ↗</button><button class="launch-demo" disabled>${ja?'カメラなしで練習':'PRACTICE'}</button><button class="launch-howto">${ja?'遊び方':'HOW TO PLAY'}</button></div><p class="launch-status" role="status"></p><p>${ja?'マイク不要。映像は端末内で処理。CREATORの保存動画は無音です。':'No microphone. Camera stays local. CREATOR exports are silent.'}</p></div></section>`;}
export function readOptions(root){return{creator:root.querySelector('.sd-creator')?.checked,faceMode:root.querySelector('.sd-face-mode')?.value??'ORIGINAL'};}
export function howtoMarkup(game,locale){const ja=locale==='ja';return `<h2 id="sheet-title">FINGER GUN: SHOWDOWN</h2><p>${ja?'指で狙い、口を開けて「BAN!」。6発撃ったら手を画面下へ下げ、0.3秒キープしてリロード。':'Point to aim. Open your mouth: BAN! Lower your hand for 0.3 seconds to reload six shots.'}</p><p>${ja?'赤い敵を撃つ。青い市民（SAFE ♥）は撃たない。金色はボーナス。残り7秒でHIGH NOON、最後に賞金首！':'Shoot red outlaws. Protect blue civilians (SAFE ♥). Gold earns a bonus. HIGH NOON at seven seconds left, then the final bounty!'}</p><p>${ja?'カメラなし：タップ / Spaceで射撃、Rで装填。Pで一時停止。口を閉じてから開くたびに1発。マイクは使いません。':'Practice: tap / Space to fire, R to reload, P to pause. Close and reopen your mouth for each shot. No microphone.'}</p><p>Art: Imagegen · SE: Kenney (CC0) · BGM: <a href="https://opentracks.com/bgm/detail/1978">8-bit Aggressive1 / もっぴーさうんど</a></p>`;}
export function resultMarkup(game,r,locale){return `<section class="sd-result"><p>SHOWDOWN COMPLETE · ${r.source==='demo'?'PRACTICE':'CAMERA'}</p><h2>${r.title}</h2><strong>${r.score.toLocaleString()}</strong><dl><div><dt>BEST COMBO</dt><dd>×${r.bestCombo}</dd></div><div><dt>QUICK DRAW</dt><dd>${r.quick}</dd></div><div><dt>ACCURACY</dt><dd>${r.accuracy}%</dd></div></dl><p>FINAL SHOT · ${r.final?'PERFECT':'SO CLOSE!'}</p>${r.creator?'<div class="sd-replay"><h3>BEST MOMENT · 7 SEC</h3><canvas width="270" height="480"></canvas><p><button class="sd-replay-play">REPLAY ▶</button> <button class="sd-save">SAVE ↓</button></p><p class="sd-export-status" role="status">LOCAL · SILENT VIDEO</p></div>':''}<div class="result-actions"><button data-result-action="retry">${locale==='ja'?'もう一度':'AGAIN'} ↗</button><button data-result-action="share">SHARE</button><button data-result-action="next">NEXT →</button></div></section>`;}
export const mountResult=mountReplay;
export function discardResult(r){if(r?.creator){r.creator.frames.forEach(f=>f.canvas.width=0);r.creator.frames=[];}}
export function paint(){}
