export const messages = {
  ja: {
    camera: "アウトカメラ", demo: "デモ · 画面の素材で練習", loading: "アウトカメラを準備中…", error: "アウトカメラを使えません。カメラの許可とHTTPS接続を確認してください。", retryCamera: "カメラを再試行", tryDemo: "デモで試す",
    background: "ガイドから物を外して、背景をセット。", calibrating: "そのまま1秒、静止してください", capture: "背景をセット", recapture: "背景を撮り直す", look: "LOOK GOOD?", review: "見た目が合っていれば、それが正解。", yes: "いい感じ！", retry: "合わせ直す", next: "次のステージ →", finish: "完成した世界を見る →", clear: "PERFECT FIT!", selfClear: "YOUR FIT!", part: "次は、柱をつくろう。", paused: "一時停止中", resume: "続ける", interrupted: "映像が止まりました。カメラを再接続してください。",
    find: "身の回りの形を、白いガイドへ。", almost: "ALMOST", ready: "LOCK READY", locked: "LOCK!", complete: "WORLD COMPLETE", summary: "5つの世界を、あなたの見立てで。", selfJudged: "回は自分の見た目で決定", resultCamera: "カメラの結果", resultDemo: "デモの結果", rotate: "角度", size: "大きさ", demoHint: "素材をドラッグして合わせる", keys: "矢印で移動 · Q/Eで回転 · −/+で拡縮 · SpaceでLOCK", hint: "スマホを動かそう。近づく・離れる・傾ける。", moonHint: "小さく見せるなら、スマホを離してみよう。", dark: "暗くて採点できません。見た目で決めよう。", motion: "背景が変わりました。見た目で決めよう。", uncertain: "うまく読み取れませんでした。見た目で決めよう。", unavailable: "画像の採点ができません。見た目で決めよう。", board: "欠けた世界。白いガイドに現実の形を合わせてLOCK。", progress: "ステージ", reset: "素材を戻す", pause: "一時停止", local: "画像はこの端末内だけで処理します。",
  },
  en: {
    camera: "REAR CAMERA", demo: "DEMO · PRACTICE MATERIAL", loading: "Opening the rear camera…", error: "Rear camera unavailable. Check camera permission and use HTTPS.", retryCamera: "RETRY CAMERA", tryDemo: "TRY DEMO",
    background: "Clear the guide, then set the background.", calibrating: "Hold still for one second", capture: "SET BACKGROUND", recapture: "RESET BACKGROUND", look: "LOOK GOOD?", review: "If it looks right to you, it fits.", yes: "LOOKS GOOD!", retry: "TRY AGAIN", next: "NEXT STAGE →", finish: "SEE YOUR WORLD →", clear: "PERFECT FIT!", selfClear: "YOUR FIT!", part: "Now, make a pillar.", paused: "PAUSED", resume: "CONTINUE", interrupted: "The camera stopped. Reconnect to continue.",
    find: "Bring a real shape into the white guide.", almost: "ALMOST", ready: "LOCK READY", locked: "LOCK!", complete: "WORLD COMPLETE", summary: "Five little worlds. Your way of seeing.", selfJudged: "fits judged by you", resultCamera: "Camera result", resultDemo: "Demo result", rotate: "ANGLE", size: "SIZE", demoHint: "Drag the material into the guide", keys: "Arrows move · Q/E rotate · −/+ resize · Space locks", hint: "Move your phone. Closer, farther, tilt.", moonHint: "Move your phone farther away to make it look smaller.", dark: "Too dark to score. Trust your eyes.", motion: "The background moved. Trust your eyes.", uncertain: "Could not read the shape. Trust your eyes.", unavailable: "Scoring unavailable. Trust your eyes.", board: "A missing world. Align a real shape with the white guide and LOCK.", progress: "Stage", reset: "RESET MATERIAL", pause: "PAUSE", local: "Images are processed only on this device.",
  },
};
