import { SPIRITS } from './copy.js';
import { escapeHtml as esc } from '../platform/copy.js';
import './style.css';
// The launch screen is rendered entirely by DOM/CSS; the shell calls this hook.
export function paint() {}
export function launchMarkup(game, locale) {
  const ja = locale === 'ja';
  return `<section class="maru-entry"><div class="maru-entry-meta"><span>EXP–062 / MARU MAGIC</span><span>A LITTLE SUMMONING RITUAL</span></div><div class="maru-entry-grid"><div class="maru-entry-art"><i class="maru-mini" data-spirit="1" aria-hidden="true"></i><span>EVERY CIRCLE HAS A SOUL.</span></div><div class="maru-entry-copy"><span>${ja ? 'まる召喚 / SOLO' : 'SOLO / FINGERTIP MAGIC'}</span><h1>MARU<br> <em>MAGIC</em></h1><h2>${ja ? 'まるを描くと、<br>何かが生まれる。' : 'One circle.<br>A little life.'}</h2><p>${ja ? 'きれいなまるには、きらめく精霊。<br>へんてこなまるにも、誇らしげな精霊。' : 'A lovely circle brings a luminous spirit.<br>A wonky circle brings a very proud potato.'}</p><div class="maru-entry-steps"><span><b>01</b>${ja ? '描く' : 'DRAW'}</span><span><b>02</b>${ja ? '判定' : 'JUDGE'}</span><span><b>03</b>${ja ? '召喚！' : 'SUMMON!'}</span></div><div class="launch-controls"><button class="launch-camera" disabled type="button">${ja ? '指先で、召喚する / PLAY' : 'SUMMON WITH YOUR FINGER'} ✦</button><button class="launch-demo" disabled type="button">${ja ? 'タッチで遊んでみる' : 'TRY TOUCH PRACTICE'}</button><button class="launch-howto" type="button">${ja ? '遊び方・採点・素材について' : 'HOW TO PLAY, SCORING & CREDITS'} ↗</button></div><p class="launch-status" role="status"></p></div></div><div class="maru-roster">${SPIRITS.map((s,i)=>`<div><i class="maru-mini" data-spirit="${i}" aria-hidden="true"></i><b>${s[ja ? 'ja' : 'en']}</b><span>${s.band}</span></div>`).join('')}</div><details class="maru-entry-privacy"><summary>${ja ? 'カメラと記録について' : 'CAMERA & RECORDS'}</summary><p>${esc(game[ja ? 'privacyJa' : 'privacyEn'])}</p></details></section>`;
}
export function howtoMarkup(game, locale) {
  const ja = locale === 'ja';
  return `<h2 id="sheet-title">MARU MAGIC / ${ja ? 'まる召喚' : 'HOW TO PLAY'}</h2><ol><li>${ja ? 'スマホを立て、人差し指を見せて0.3秒静止。光の輪が満ちて「準備OK！」が出たら、描き始められます。' : 'Prop up your phone. Show your index finger and hold still for 0.3 seconds. Wait for the filling ring and the big READY cue.'}</li><li>${ja ? '指先を動かして、一周だけ円を描く。始めた場所の緑の印に戻ると自動で召喚！' : 'Move your fingertip to draw one circle. Return to the green starting mark to summon automatically!'}</li><li>${ja ? '「もう一度」に指先を合わせ、光がたまるまで約0.7秒止めると再挑戦。ボタンをタップしてもOK。タッチ練習では、画面に触れて円を描く。指を離しても採点できます。' : 'Hold your fingertip over AGAIN for about 0.7 seconds to retry as the light fills. Tapping works too. In touch practice, press and draw. Releasing also submits your stroke.'}</li></ol><p>${ja ? '丸さ75％・閉じ具合15％・滑らかさ10％。速さは点数に加算しません。直線・小さすぎる円・未完成・逆走・複数周は49点以下。最高得点と「80点以上の完成した円」の最速だけ端末保存。' : 'Roundness 75%, closure 15%, smoothness 10%. No speed bonus. Lines, tiny or unfinished circles, backtracking and multiple loops are capped at 49. Your best score and fastest complete 80+ circle are saved locally.'}</p><p>${ja ? '描き始めから8秒で採点。指を見失ったら最大0.55秒待ち、長い中断は点数を付けずにやり直せます。一時停止や別画面への移動で、描きかけはリセットします。' : 'Each stroke has an 8-second input timeout. Brief tracking loss gets 0.55 seconds of grace. A longer interruption resets without a score. Pausing or leaving the tab resets unfinished strokes.'}</p><p>${ja ? '精霊画像：Imagegen。紙と召喚のアクセント：Kenney RPG Audio（CC0）。4段階の召喚音・ファンファーレ：オリジナルWeb Audio。' : 'Spirits: Imagegen. Paper and summon accents: Kenney RPG Audio (CC0). Four summon motifs and fanfare: original Web Audio.'}</p><p>${esc(game[ja ? 'privacyJa' : 'privacyEn'])}</p>`;
}
