import { cover, fishArt } from './assets.js';
import { FISH } from './core.js';
import { escapeHtml as esc } from '../platform/copy.js';
import './hook.css';

export function launchMarkup(game, locale) {
  const ja = locale === 'ja';
  return `<section class="hook-entry"><div class="hook-meta"><span>EXP-060 / CAMERA FISHING</span><span>ONE HAND. ONE BIG CATCH.</span></div><div class="hook-entry-grid">
    <div class="hook-cover"><img src="${cover}" width="768" height="1365" alt="${ja ? '大きな青いマグロがきらめく海から飛び出す' : 'A giant blue tuna leaps out of a sparkling turquoise ocean'}"><div class="hook-cover-title"><span>CAST. HOOK. PULL.</span><h1>HOOK<span>!</span></h1></div><span class="hook-sticker">30<br><small>SECONDS<br>OF FISH FIGHT.</small></span><span class="hook-cover-bottom">THE OCEAN HAS<br>A SENSE OF HUMOR.</span></div>
    <div class="hook-entry-copy"><p class="hook-kicker">YOUR BODY. YOUR FISHING ROD.</p><h2>${ja ? '食いついたら、<br><em>身体ごと引け。</em>' : 'When it bites,<br><em>put your body<br>into it.</em>'}</h2><p class="hook-description">${ja ? 'カメラの中に、小さな海。<br>片手ひとつで、大きな魚と大げんか。' : 'A little ocean in your camera.<br>One hand. A ridiculously big fish fight.'}</p>
    <ol class="hook-steps"><li><span>01</span><div><b>CAST.</b><p>${ja ? '手をシュッと振って投げる' : 'Swing your hand to cast'}</p></div><i>↗</i></li><li><span>02</span><div><b>HOOK.</b><p>${ja ? 'HIT!!が出たら、手を上へ' : 'HIT!! means pull your hand UP'}</p></div><i>↑</i></li><li><span>03</span><div><b>PULL.</b><p>${ja ? '魚が右なら、手は左へ！' : 'Fish goes right? Pull LEFT!'}</p></div><i>↔</i></li></ol>
    <div class="launch-controls hook-launch"><button class="launch-camera hook-primary" type="button" disabled>${ja ? '海へ出る / PLAY' : 'LET’S GO FISHING'} ↗</button><button class="launch-demo hook-secondary" type="button" disabled>${ja ? 'カメラなしで練習' : 'PRACTICE WITHOUT CAMERA'}</button><button class="launch-howto hook-text" type="button">${ja ? '遊び方と素材クレジット' : 'HOW TO PLAY & CREDITS'} ↗</button></div><p class="launch-status" role="status"></p>
    <p class="hook-entry-foot">${ja ? 'スマホは立てて、片手が映る距離で。<br>手の形は自由。最初の1匹はアジ。' : 'Prop up your phone. Keep one hand in frame.<br>Any hand shape. Your first fish is an aji.'}</p><details class="hook-privacy"><summary>${ja ? 'カメラと写真について' : 'CAMERA & PHOTOS'}</summary><p>${esc(game[ja ? 'privacyJa' : 'privacyEn'])}</p></details></div></div>
    <div class="hook-roster"><span>${ja ? '本日の釣れるもの' : 'TODAY’S POSSIBLE CATCHES'}</span>${FISH.map(f => `<div><img src="${fishArt[f.id]}" alt="${esc(f[ja ? 'ja' : 'en'])}"><b>${f.id === 'HUMAN' ? '???' : f.id}</b></div>`).join('')}</div></section>`;
}
export function howtoMarkup(game, locale) {
  const ja = locale === 'ja';
  return `<h2 id="sheet-title">HOOK! · ${ja ? '遊び方' : 'HOW TO PLAY'}</h2><p>${ja ? '30秒で何匹釣れる？ 最初はアジで練習。3匹連続でFEVER、残り時間+5秒！' : 'How many fish in 30 seconds? Learn with an aji. Three catches in a row earn FEVER and five more seconds!'}</p><ol><li>${ja ? '手を大きく振って投げる。画面タップでも投げられます。' : 'Swing one hand to cast. A tap works too.'}</li><li>${ja ? '赤いウキが沈んでHIT!!が出たら、手を上へ！ 小さな揺れは偽物のアタリです。' : 'When the red float dives and HIT!! appears, pull UP! Small nibbles are fake bites.'}</li><li>${ja ? '魚と逆方向へ手を動かし、緑のテンションをキープ。引きすぎたら中央へ戻す。' : 'Pull opposite the fish and keep the tension green. Ease toward center if it gets too tight.'}</li></ol><p>${ja ? '練習：タップ / Spaceで投げる。上スワイプ / ↑ / 合わせるボタンでHOOK。横ドラッグか左右ボタン長押し / ← → / A Dで引く。Pで一時停止。' : 'Practice: tap / Space to cast. Swipe UP / ↑ / HOOK button to hook. Drag sideways or hold an arrow / ← → / A D to pull. P pauses.'}</p><p>${ja ? '手が消えたら魚とタイマーが止まります。中央に戻し、手を映して復帰。人面魚を逃がすと実績「同業者」。' : 'Missing hands pause the fish and timer. Return to center to recover. Release the human fish to unlock COLLEAGUE.'}</p><p>${ja ? '魚・カバー：Imagegen。竿の振り・着水のアクセント：Kenney（CC0）。水しぶきや成功音はWeb Audioで合成。' : 'Fish and cover: Imagegen. Cast and impact accents: Kenney (CC0). Water and success tones: Web Audio.'}</p><p>${esc(game[ja ? 'privacyJa' : 'privacyEn'])}</p>`;
}
export function resultMarkup(game, r, locale) {
  const ja = locale === 'ja', biggest = r.biggest, art = biggest ? fishArt[biggest.id] : fishArt.AJI;
  return `<section class="hook-result"><div class="hook-meta"><span>HOOK! / YOUR FISHING REPORT</span><span>${Math.round(r.elapsed)} SEC · ${r.source === 'demo' ? 'PRACTICE' : 'LIVE CAMERA'}</span></div><div class="hook-result-grid"><div class="hook-result-art">${r.photo ? `<img class="hook-memory" alt="${ja ? '自分と釣り上げた魚の記念写真' : 'You and your catch'}">` : `<img class="hook-trophy" src="${art}" alt="${biggest?.id || 'AJI'}">`}<span>${biggest ? 'BIGGEST CATCH' : 'THE FISH GOT LUCKY.'}</span><strong>${biggest ? biggest.size : '…'}<small>${biggest ? 'cm' : ''}</small></strong></div><div class="hook-result-copy"><p class="hook-kicker">${r.catches.length ? 'A VERY GOOD DAY TO GET WET.' : 'THERE’S ALWAYS ANOTHER CAST.'}</p><h2>${ja ? r.catches.length ? 'いい魚、<br><em>いただきました。</em>' : '次の一投で、<br><em>大物を。</em>' : r.catches.length ? 'That’s a<br><em>good catch.</em>' : 'One more<br><em>cast?</em>'}</h2><p class="hook-result-score"><strong>${r.score.toLocaleString('en-US')}</strong> PT</p><dl class="hook-result-stats"><div><dt>${ja ? '釣れた数' : 'CATCHES'}</dt><dd>${r.catches.length}</dd></div><div><dt>PERFECT</dt><dd>${r.perfects}</dd></div><div><dt>BEST COMBO</dt><dd>×${r.bestCombo}</dd></div></dl>${r.releasedHuman ? `<p class="hook-achievement">✧ ${ja ? '実績解除：同業者' : 'ACHIEVEMENT: COLLEAGUE'}</p>` : ''}${r.source === 'demo' ? `<p class="hook-practice-note">${ja ? 'カメラなしの練習記録です。' : 'This is a camera-free practice record.'}</p>` : ''}
    <div class="result-actions hook-result-actions"><button class="hook-primary" type="button" data-result-action="retry">${ja ? 'もう一度、釣りに行く' : 'ONE MORE FISH FIGHT'} ↗</button>${r.photo ? `<button class="hook-secondary hook-save-photo" type="button">${ja ? '記念写真を保存' : 'SAVE CATCH PHOTO'} ↓</button>` : ''}<button class="hook-secondary" type="button" data-result-action="share">${ja ? '釣果を共有' : 'SHARE MY CATCH'}</button><button class="hook-text" type="button" data-result-action="next">NEXT →</button></div></div></div>${r.catches.length ? `<div class="hook-catch-log"><p class="hook-kicker">TODAY’S CATCH / ${r.catches.length}</p>${r.catches.map(f => `<article><img src="${fishArt[f.id]}" alt="${f.id}"><div><b>${f.id} · ${f.size} cm</b><p>SIZE +${f.sizePoints} · HOOK +${f.hookPoints} · TENSION +${f.tensionPoints} · SPEED +${f.speedPoints}</p></div><strong>+${f.points}</strong></article>`).join('')}</div>` : ''}</section>`;
}
export function mountResult(root, r) {
  if (!r.photo) return; const url = URL.createObjectURL(r.photo), abort = new AbortController(); root.querySelector('.hook-memory').src = url;
  root.querySelector('.hook-save-photo').addEventListener('click', () => { const a = document.createElement('a'); a.href = url; a.download = 'hook-big-catch.png'; a.click(); }, { signal: abort.signal });
  return () => { abort.abort(); URL.revokeObjectURL(url); };
}
export function discardResult(r) { if (r) r.photo = null; }
export function paint() {}
