import './style.css';
import { escapeHtml as esc } from '../../platform/copy.js';
export function launchMarkup(game, locale) {
  const ja = locale === 'ja', maestro = game.id === 'solo-maestro';
  return `<section class="cmi-entry ${maestro ? 'cmi-entry-maestro' : 'cmi-entry-world'}"><div class="cmi-entry-content"><p class="cmi-kicker">${maestro ? 'A LITTLE ORCHESTRA. ALL YOURS.' : 'CAMERA INSTRUMENT PLAYGROUND'}</p><h1>${maestro ? 'MAESTRO' : 'WORLD<br><em>INSTRUMENT</em>'}</h1><p class="cmi-tagline">${maestro ? ja ? '手を振った瞬間、<br>音楽がきみについてくる。' : 'Move your hands.<br>The music follows you.' : ja ? '机も、コップも、ぬいぐるみも。<br>好きな物が、きみの楽器になる。' : 'A cup. A toy. Your tabletop.<br>Turn everyday things into music.'}</p>
    ${maestro ? '' : '<div class="cmi-world-poster" aria-hidden="true"><small>TOUCH THE WORLD. MAKE A MELODY.</small><span>🍌</span><span>🥤</span><span>🧸</span><b>C</b><b>E</b><b>G</b></div>'}
    <div class="cmi-entry-bottom"><p>${maestro ? ja ? '手を上げよう。それだけで、小さな演奏会が始まる。<br>時間制限なし。スコアなし。きみだけの指揮。' : 'Raise a hand. Your little concert begins.<br>No timer. No score. Just your orchestra.' : ja ? 'アウトカメラを向けて、好きな物を3つタップ。<br>トントンすると、音が鳴る。最大5つまで。' : 'Point your rear camera. Pick three objects.<br>Give them a tap. Up to five sound spots.'}</p>
    <div class="launch-controls"><button class="launch-camera cmi-primary" type="button" disabled>PLAY ↗</button><button class="launch-demo" type="button" disabled>${ja ? 'カメラなしの練習' : 'Camera-free practice'}</button><button class="launch-howto" type="button">${ja ? '遊び方・素材' : 'HOW TO PLAY'}</button></div><p class="launch-status" role="status"></p><details><summary>${ja ? 'カメラとプライバシー' : 'Camera & privacy'}</summary><p>${esc(game[ja ? 'privacyJa' : 'privacyEn'])}</p></details></div></div></section>`;
}
export function howtoMarkup(game, locale) {
  const ja = locale === 'ja', maestro = game.id === 'solo-maestro';
  return `<h2 id="sheet-title">${maestro ? 'MAESTRO' : 'CAMERA INSTRUMENT'}</h2><p>${maestro ? ja ? '手を上げると弦がスタート。両腕を広げると全員が参加。左へ両手を向けると弦だけ、右で金管、下でドラム。両手を大きく動かして急停止するとCUT。全員が大きく演奏している時に両手を強く下へ振るとフィナーレ！' : 'Raise a hand to start strings. Spread both arms for the whole orchestra. Point both hands left for strings only, right for brass, down for drums. Move both hands, then freeze for CUT. With everyone playing loudly, bring both hands down hard for a finale!' : ja ? '画面の好きな物を3回タップして音を置こう。次の音は指を一度離してからトン。＋ADD SOUNDで5つまで。位置・削除でドラッグして移動、タップして削除。MELODY / DRUM / TOYを切替できます。' : 'Tap three objects on screen to add sound spots. Lift your finger between hits. Add up to five spots. EDIT lets you drag to move and tap to remove. Choose MELODY, DRUM or TOY.'}</p><p>${maestro ? ja ? '練習：Spaceで開始、1/2/3でパート、↑↓で強弱、XでCUT、Fでフィナーレ。スマホではボタンとスライダー。' : 'Practice: Space starts, 1/2/3 select sections, ↑↓ change intensity, X cuts and F triggers a finale. Or use buttons and the slider.' : ja ? '練習：音スポットをタップ、または1〜5キー。5つ自動配置ですぐに演奏できます。' : 'Practice: tap sound spots or use keys 1–5. The five-spot preset starts you quickly.'}</p>
    <p>Music / samples: <a href="https://github.com/sgossner/VSCO-2-CE" target="_blank" rel="noopener noreferrer">VSCO 2 Community Edition</a> · CC0 · Sam Gossner / Simon Dalzell / Elan Hickler. ${maestro ? 'Little Theatre · original 32-second, 120 BPM arrangement.' : ''}</p>
    ${maestro ? '<p>SE: <a href="https://otologic.jp/free/se/applause-cheer01.html" target="_blank" rel="noopener noreferrer">OtoLogic · 拍手 群衆03-3</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">CC BY 4.0</a> · volume/length/encoding edited. Kenney Interface Sounds · CC0.</p>' : '<p>Optional BGM: <a href="https://opentracks.com/bgm/detail/7044" target="_blank" rel="noopener noreferrer">おもちゃの一日 / いまたく</a> · OpenTracks.</p>'}
    <p>Artwork: OpenAI Imagegen.</p><p>${esc(game[ja ? 'privacyJa' : 'privacyEn'])}</p>`;
}
export function paint() {}
