const ja = {
  tagline: '笑ったら負け。カメラの中の自分が、一番の敵。', steps: [['真顔をセット。', 'カメラに顔を入れて、口を閉じてリラックス。'], ['15秒、笑わない。', '小鳥、巨大な鼻、遅れる顔。そして自分の分身。'], ['最後の3秒を耐えろ。', 'FINAL ATTACK。笑った瞬間は、ちゃんと押さえます。']],
  practice: 'カメラなしで練習', howto: '遊び方', privacy: 'カメラとリプレイについて', demo: 'PRACTICE · カメラなし', camera: 'FRONT CAMERA', loading: 'カメラを準備中…', model: '初回は顔の認識モデルを読み込みます。', permission: 'カメラの使用を許可してください。', error: 'カメラを使えませんでした', errorHint: 'カメラの権限を確認するか、練習で遊べます。', reconnect: 'カメラを再接続', framing: 'ひとりで、顔をカメラの中へ。', neutral: '口を閉じて、真顔を800ms。', multiple: 'ひとりずつ挑戦してね。', lost: '顔を見失いました', lostHint: 'タイマーは停止中。顔を戻して真顔をキープ。', paused: 'PAUSED', resume: 'つづける', pause: '一時停止', start: 'START · 真顔で挑戦', recalibrate: '真顔を測り直す', ready: '真顔、セット完了。', hint: '笑わず、顔を画面に入れ続けてね。', demoHint: '「笑う」を長押し、または L キー。400ms続くと負け。', smile: '笑う 😂', sfx: '効果音', replay: 'もう一度見る', save: '動画を保存', best: 'BEST', again: 'もう一度挑戦', next: '次のゲーム', share: '記録をシェア', caught: 'この顔、押さえました。', survived: '真顔のまま、15秒。お見事。', local: '直前1.5秒 → 笑った瞬間。映像は端末内だけ。', silent: '保存する動画は音声なしです。', preparing: '動画を準備しています…', saved: '動画を保存しました。', unsupported: 'このブラウザではリプレイのみ利用できます。', saveError: '動画を保存できませんでした。もう一度お試しください。', faceChoice: 'リプレイに残す顔を選ぶ', ORIGINAL: '自分の顔', EFFECT: 'ピクセル顔', HIDE: 'イラスト顔', creatorNotice: '直前1.5秒のリプレイと静止画を端末内に保持。退出時に破棄します。動画保存は自分で選べます。', weakness: '前の反応、覚えました。次はちょっと多めに。', normal: 'NORMAL · 15 SEC', guide: '最初に真顔を測り、3・2・1でスタート。口角・口の開き・頬・目の細まりを合わせて、笑顔が400ms続いたらアウト。顔が消えたときや別の顔が映ったときはタイマーを止めます。',
};
const en = {
  tagline: 'Your own face. Your worst enemy. Don’t laugh.', steps: [['Set your serious face.', 'One face in frame. Close your mouth and relax.'], ['Hold it for 15 seconds.', 'A tiny bird. A giant nose. Delays. Copies of you.'], ['Survive the last 3 seconds.', 'FINAL ATTACK. We catch the moment you crack.']],
  practice: 'Camera-free practice', howto: 'How to play', privacy: 'Camera & replay', demo: 'PRACTICE · NO CAMERA', camera: 'FRONT CAMERA', loading: 'Getting your camera ready…', model: 'The face model downloads on first use.', permission: 'Please allow camera access.', error: 'Camera unavailable', errorHint: 'Check camera permission, or try camera-free practice.', reconnect: 'Reconnect camera', framing: 'One face. Inside the frame.', neutral: 'Relax. Close your mouth for 800ms.', multiple: 'One player at a time, please.', lost: 'Face lost', lostHint: 'Timer paused. Return to frame with a straight face.', paused: 'PAUSED', resume: 'Resume', pause: 'Pause', start: 'START · Keep it straight', recalibrate: 'Reset serious face', ready: 'Serious face. Set.', hint: 'Keep your face in frame. Keep a straight face.', demoHint: 'Hold “Laugh” or the L key. 400ms of smiling ends the round.', smile: 'Laugh 😂', sfx: 'SFX', replay: 'Replay', save: 'Save clip', best: 'BEST', again: 'Try again', next: 'Next game', share: 'Share score', caught: 'We got that face.', survived: '15 seconds. Still serious. Impressive.', local: 'The last 1.5 seconds → caught in the act. Only on your device.', silent: 'Saved clips are silent.', preparing: 'Preparing your clip…', saved: 'Clip saved.', unsupported: 'This browser supports replay only.', saveError: 'Could not save. Try again.', faceChoice: 'Choose the face in your replay', ORIGINAL: 'Your face', EFFECT: 'Pixel face', HIDE: 'Illustrated face', creatorNotice: 'The last 1.5 seconds and a still stay in device memory and are discarded on exit. Saving a clip is your choice.', weakness: 'We remembered your reaction. A little more of that next time.', normal: 'NORMAL · 15 SEC', guide: 'Calibrate a relaxed straight face, then 3, 2, 1. Mouth corners, mouth opening, cheeks and eye narrowing contribute to the smile signal. A smile sustained for 400ms ends the round. Missing or multiple faces pause the timer.',
};
export const copy = locale => locale === 'ja' ? ja : en;
