import './rockPaperBoom.css';
export function launchMarkup(game, locale) {
  const ja = locale === 'ja';
  return `<section class="rpb-entry"><div class="rpb-cover"><img src="/previews/rock-paper-boom.webp" width="768" height="1152" alt="${ja ? 'じゃんけんする二人の上で、巨大な岩の拳と光のハサミが激突' : 'Two friends play rock-paper-scissors beneath a giant volcanic fist and energy scissors'}"><div class="rpb-cover-title"><span class="rpb-kicker">EXP-061 / TWO PLAYER CHAOS</span><h1>ROCK<br>PAPER<br><em>BOOM!</em></h1></div><span class="rpb-cover-caption">JUST JANKEN. WITH CONSEQUENCES.</span></div>
    <div class="rpb-entry-copy"><span class="rpb-kicker">2 PLAYERS · 6 SECONDS · BIG TROUBLE</span><h2>${ja ? 'ただのじゃんけん。<br>結果は、ただごとじゃない。' : 'Small hands.<br>Ridiculous consequences.'}</h2><p>${ja ? '二人でグー・チョキ・パー。勝負が決まったら、世界が爆発する。あいこだって、必殺技。' : 'Rock, paper, scissors. Then the world goes BOOM. Even a draw deserves a ridiculous finish.'}</p><ol class="rpb-steps"><li><b>01</b><div><strong>${ja ? '二人をアウトカメラに映す' : 'Frame both friends'}</strong><p>${ja ? '左がPLAYER 1、右がPLAYER 2。' : 'Rear camera. P1 left, P2 right.'}</p></div></li><li><b>02</b><div><strong>${ja ? 'SHOOT! で手を出す' : 'Throw on SHOOT!'}</strong><p>${ja ? '一人ひとつの手を、左右の枠の中へ。' : 'One hand per zone. Hold it for a moment.'}</p></div></li><li><b>03</b><div><strong>${ja ? '一瞬、静止。そして爆裂。' : 'Freeze. Then BOOM.'}</strong><p>${ja ? '笑ったら、AGAIN? でもう一戦。' : 'Laugh. Tap AGAIN? Keep it going.'}</p></div></li></ol><div class="launch-controls rpb-launch-controls"><button class="launch-camera" type="button" disabled>${ja ? 'カメラで爆裂じゃんけん' : 'PLAY WITH CAMERA'} ↗</button><button class="launch-demo" type="button" disabled>${ja ? 'カメラなしで試す' : 'TRY WITHOUT CAMERA'}</button><button class="launch-howto" type="button" disabled>${ja ? '遊び方・素材クレジット' : 'HOW TO PLAY & CREDITS'} ＋</button></div><p class="launch-status" role="status"></p><details class="rpb-privacy"><summary>${ja ? 'カメラとプライバシー' : 'Camera & privacy'}</summary><p>${game[ja ? 'privacyJa' : 'privacyEn']}</p></details></div></section>`;
}
export function howtoMarkup(game, locale) {
  const ja = locale === 'ja';
  return `<h2 id="sheet-title">ROCK PAPER BOOM!</h2><p>${ja ? 'スマホのアウトカメラに二人を映します。左がP1、右がP2。片手ずつHAND ZONEに構えるとカウント開始。SHOOT!で手を出し、少しキープ。判定できなければ自動で出し直します。' : 'Frame two friends with your rear camera. P1 left, P2 right. Hold one hand in each zone to begin the count. Throw on SHOOT! and hold briefly. Unclear hands get a retry.'}</p><p>✊ ROCK &gt; ✌️ SCISSORS &gt; 🖐 PAPER &gt; ✊ ROCK</p><p>${ja ? '練習：P1はA/S/D、P2はJ/K/L。または画面のボタン。Pで一時停止。全9通りの演出を試せます。' : 'Practice: P1 A/S/D, P2 J/K/L, or tap the buttons. P pauses. All nine matchups are playable.'}</p><p>${ja ? 'SE: Kenney Impact Sounds / RPG Audio（CC0）。画像: OpenAI Imagegen。' : 'SE: Kenney Impact Sounds / RPG Audio (CC0). Artwork: OpenAI Imagegen.'}</p><p>${game[ja ? 'privacyJa' : 'privacyEn']}</p>`;
}
export function paint() {}
